"""made name uniqe

Revision ID: 3dab9d1d67e4
Revises: fa447bf7dc95
Create Date: 2025-04-24 19:10:45.290015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dab9d1d67e4'
down_revision: Union[str, None] = 'fa447bf7dc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_user_name'), 'users', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_user_name'), 'users', type_='unique')
    # ### end Alembic commands ###
