"""add subscribe column2

Revision ID: b44b58532450
Revises: 20bd2c1bcb24
Create Date: 2025-04-29 21:29:17.177836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44b58532450'
down_revision: Union[str, None] = '20bd2c1bcb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('sub_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], name=op.f('fk_subscriptions_follower_id_users')),
    sa.ForeignKeyConstraint(['following_id'], ['users.user_id'], name=op.f('fk_subscriptions_following_id_users')),
    sa.PrimaryKeyConstraint('sub_id', name=op.f('pk_subscriptions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
